import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { prisma } from '@/lib/prisma'
import { PurchaseOrderStatus, TransactionType } from '@prisma/client'

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const searchParams = request.nextUrl.searchParams
    const status = searchParams.get('status')

    const purchaseOrders = await prisma.purchaseOrder.findMany({
      where: status ? { status: status as PurchaseOrderStatus } : undefined,
      include: {
        product: true,
        supplier: true,
      },
      orderBy: { createdAt: 'desc' },
    })

    return NextResponse.json(purchaseOrders)
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch purchase orders' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { supplierId, productId, quantity, autoGenerate } = body

    // Auto-generate PO when inventory is low
    if (autoGenerate) {
      if (!productId) {
        return NextResponse.json(
          { error: 'Product ID is required for auto-generation' },
          { status: 400 }
        )
      }

      // Check inventory levels across all warehouses
      const inventories = await prisma.inventory.findMany({
        where: { productId },
      })

      const productSettings = await prisma.productSetting.findUnique({
        where: { productId },
      })

      if (!productSettings) {
        return NextResponse.json(
          { error: 'Product settings not found. Cannot auto-generate PO.' },
          { status: 400 }
        )
      }

      const totalQuantity = inventories.reduce((sum, inv) => sum + inv.quantity, 0)

      // Only create PO if total inventory is below min stock level
      if (totalQuantity >= productSettings.minStockLevel) {
        return NextResponse.json(
          { message: 'Inventory is sufficient, no PO needed', skip: true },
          { status: 200 }
        )
      }

      // Get supplier for the product
      const productSupplier = await prisma.productSupplier.findFirst({
        where: { productId },
        include: { supplier: true },
      })

      if (!productSupplier) {
        return NextResponse.json(
          { error: 'No supplier associated with this product' },
          { status: 400 }
        )
      }

      // Calculate reorder quantity (typically minStockLevel * 2 or a fixed multiplier)
      const reorderQuantity = productSettings.minStockLevel * 2

      // Check if there's already a pending PO for this product
      const existingPO = await prisma.purchaseOrder.findFirst({
        where: {
          productId,
          status: PurchaseOrderStatus.PENDING,
        },
      })

      if (existingPO) {
        return NextResponse.json(
          { message: 'Pending purchase order already exists', purchaseOrder: existingPO },
          { status: 200 }
        )
      }

      const purchaseOrder = await prisma.purchaseOrder.create({
        data: {
          supplierId: productSupplier.supplierId,
          productId,
          quantity: reorderQuantity,
          status: PurchaseOrderStatus.PENDING,
        },
        include: {
          product: true,
          supplier: true,
        },
      })

      return NextResponse.json({ 
        purchaseOrder, 
        autoGenerated: true,
        reason: `Inventory (${totalQuantity}) below min stock level (${productSettings.minStockLevel})` 
      }, { status: 201 })
    }

    // Manual PO creation
    if (!supplierId || !productId || !quantity) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    const purchaseOrder = await prisma.purchaseOrder.create({
      data: {
        supplierId,
        productId,
        quantity,
        status: PurchaseOrderStatus.PENDING,
      },
      include: {
        product: true,
        supplier: true,
      },
    })

    return NextResponse.json(purchaseOrder, { status: 201 })
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || 'Failed to create purchase order' },
      { status: 500 }
    )
  }
}

