import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { prisma } from '@/lib/prisma'
import { PurchaseOrderStatus, TransactionType } from '@prisma/client'

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const searchParams = request.nextUrl.searchParams
    const status = searchParams.get('status')

    const purchaseOrders = await prisma.purchaseOrder.findMany({
      where: status ? { status: status as PurchaseOrderStatus } : undefined,
      include: {
        product: true,
        supplier: true,
      },
      orderBy: { createdAt: 'desc' },
    })

    // Add pricing information from ProductSupplier
    const purchaseOrdersWithPricing = await Promise.all(
      purchaseOrders.map(async (po) => {
        const productSupplier = await prisma.productSupplier.findFirst({
          where: {
            productId: po.productId,
            supplierId: po.supplierId,
          },
        })
        return {
          ...po,
          unitPrice: productSupplier?.price || null,
        }
      })
    )

    return NextResponse.json(purchaseOrdersWithPricing)
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch purchase orders' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { supplierId, productId, quantity, autoGenerate } = body

    // Auto-generate PO when inventory is low
    if (autoGenerate) {
      if (!productId) {
        return NextResponse.json(
          { error: 'Product ID is required for auto-generation' },
          { status: 400 }
        )
      }

      // Check inventory levels across all warehouses
      const inventories = await prisma.inventory.findMany({
        where: { productId },
      })

      const productSettings = await prisma.productSetting.findUnique({
        where: { productId },
      })

      if (!productSettings) {
        return NextResponse.json(
          { error: 'Product settings not found. Cannot auto-generate PO.' },
          { status: 400 }
        )
      }

      const totalQuantity = inventories.reduce((sum, inv) => sum + inv.quantity, 0)

      // Only create PO if total inventory is below min stock level
      if (totalQuantity >= productSettings.minStockLevel) {
        return NextResponse.json(
          { message: 'Inventory is sufficient, no PO needed', skip: true },
          { status: 200 }
        )
      }

      // Get all suppliers linked to the product and choose the one with minimum cost
      const productSuppliers = await prisma.productSupplier.findMany({
        where: { productId },
        include: { supplier: true },
        orderBy: {
          price: 'asc', // Order by price ascending (cheapest first)
        },
      })

      if (!productSuppliers || productSuppliers.length === 0) {
        return NextResponse.json(
          { error: 'No supplier associated with this product' },
          { status: 400 }
        )
      }

      // Choose supplier with minimum cost
      const productSupplier = productSuppliers[0]

      // Calculate reorder quantity (typically minStockLevel * 2 or a fixed multiplier)
      const reorderQuantity = productSettings.minStockLevel * 2

      // Check if there's already a pending PO for this product
      const existingPO = await prisma.purchaseOrder.findFirst({
        where: {
          productId,
          status: PurchaseOrderStatus.PENDING,
        },
      })

      if (existingPO) {
        return NextResponse.json(
          { message: 'Pending purchase order already exists', purchaseOrder: existingPO },
          { status: 200 }
        )
      }

      const purchaseOrder = await prisma.purchaseOrder.create({
        data: {
          supplierId: productSupplier.supplierId,
          productId,
          quantity: reorderQuantity,
          status: PurchaseOrderStatus.PENDING,
        },
        include: {
          product: true,
          supplier: true,
        },
      })

      return NextResponse.json({ 
        purchaseOrder, 
        autoGenerated: true,
        reason: `Inventory (${totalQuantity}) below min stock level (${productSettings.minStockLevel})` 
      }, { status: 201 })
    }

    // Manual PO creation
    if (!productId || !quantity) {
      return NextResponse.json(
        { error: 'Product and quantity are required' },
        { status: 400 }
      )
    }

    // Check if product has any linked suppliers
    const productSuppliers = await prisma.productSupplier.findMany({
      where: { productId },
      orderBy: {
        price: 'asc', // Order by price ascending (cheapest first)
      },
      include: {
        supplier: true,
      },
    })

    if (!productSuppliers || productSuppliers.length === 0) {
      return NextResponse.json(
        { 
          error: 'This product has no linked suppliers. Please link a supplier to this product before creating a purchase order.',
          code: 'NO_SUPPLIERS_LINKED'
        },
        { status: 400 }
      )
    }

    // If supplierId is provided, validate it's linked. Otherwise, use the cheapest supplier
    let selectedSupplierId = supplierId
    
    if (!selectedSupplierId) {
      // Auto-select cheapest supplier if no supplier specified
      selectedSupplierId = productSuppliers[0].supplierId
    } else {
      // Validate that the provided supplier is linked to the product
      const isValidSupplier = productSuppliers.some(ps => ps.supplierId === selectedSupplierId)
      
      if (!isValidSupplier) {
        return NextResponse.json(
          { 
            error: 'The selected supplier is not linked to this product. Please select a linked supplier or we can use the cheapest linked supplier.',
            code: 'SUPPLIER_NOT_LINKED',
            availableSuppliers: productSuppliers.map(ps => ({
              id: ps.supplierId,
              name: ps.supplier.name,
              price: ps.price,
            })),
          },
          { status: 400 }
        )
      }
    }

    // Use the cheapest supplier if multiple are available and none was specified
    if (productSuppliers.length > 1 && !supplierId) {
      selectedSupplierId = productSuppliers[0].supplierId
    }

    const purchaseOrder = await prisma.purchaseOrder.create({
      data: {
        supplierId: selectedSupplierId,
        productId,
        quantity,
        status: PurchaseOrderStatus.PENDING,
      },
      include: {
        product: true,
        supplier: true,
      },
    })

    return NextResponse.json({
      ...purchaseOrder,
      autoSelectedSupplier: !supplierId && productSuppliers.length > 1,
      selectedReason: !supplierId ? 'Auto-selected cheapest supplier' : 'Manual selection',
    }, { status: 201 })
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || 'Failed to create purchase order' },
      { status: 500 }
    )
  }
}

